### ISSUE TITLE
Add the ability to link files/directories from a different location

### ISSUE THREAD

**Issue by janrito** [jbernard/dotfiles#16]
I am specifically thinking about the Sublime Text configuration directory, which is generally:

    Users/<user>/Library/Application Support/Sublime Text 2/Packages/User/

It could work something like `externals`, but the other way around:

    internals = {
      'sublimetextconf': 'Users/<user>/Library/Application Support/Sublime Text 2/Packages/User'
    }

This would make a link from `Users/<user>/Library/Application Support/Sublime Text 2/Packages/User` to a directory inside the repository called `sublimetextconf`

**Comment by jbernard** [comment]
I think I've got this done now.  In `master` you'll find the ability to add dotfiles at any nested depth, and `dotifles` will maintain the directory structure automatically.  Take it for a spin if you're interested, it's a pretty big change from the previous version and I hope to have it releases on pypi in a week or so.

Cheers
