### ISSUE TITLE
Request: whitelist setting in config file

### ISSUE THREAD

**Issue by tvdburgt** [jbernard/dotfiles#18]
For the more cautious users, a whitelist-like setting for dotfiles (in contrast to the existing 'ignore' option) could come in handy.

**Comment by jbernard** [comment]
I suspect you may not care about this anymore and after some thought, I'm not sure if there is a lot of demand for this feature still.  I accept that this might be a wrong assumption.  If I am, please reopen the bug and we can discuss.

I'm nearly done with the next major version which brings some pretty cool features, so check it out if you're interested.

Cheers
