### ISSUE TITLE
dotfile add does not work with packages

### ISSUE THREAD

**Issue by zblz** [jbernard/dotfiles#20]
Using v0.6, in my `.dotfilesrc` I have:

    packages = ['config']

However, when adding the `.config/gtk-3.0`, dotfiles complains:

    $ dotfiles -a .config/gtk-3.0
    Skipping ".config/gtk-3.0", not a dotfile

The only way I found to make it work is moving it manually to `$dotfiles_repo/config/gtk-3.0` and then running `dotfiles -s` creates the correct symlink in `.config/gtk-3.0`.

Oh, and thanks for the work, `dotfiles` is awesome!

**Comment by jbernard** [comment]
The next version supports nesting at any depth while maintaining necessary directory structure, so the old `packages` features is now gone in favor of the much better approach.  I hope to have a release up on pypi in a week or so.

Cheers
