### ISSUE TITLE
dotfiles -r deletes permanently?

### ISSUE THREAD

**Issue by florian-wagner** [jbernard/dotfiles#27]
I wanted to use this software to backup my dotfiles and now it looks like a lost them all. I did 

```
dotfiles -a .config
dotfiles -sf
dotfiles -r .config # because i didn't want to store all subfolders
```

I thought the last command restores the dotfiles to the original locations. But it looks like it is just a binding for rm -rf .config (why??) without a warning resulting in corrupt symlinks and a loss of several hours of configuration.

That is a bit dissapointing. Is there any way to restore my files? Any backup in a hidden location by any chance? I would highly appreciate your help.

**Comment by jbernard** [comment]
I'm nearly done with the next major version and I decided to remove the `force` option completely.  The reasoning is that if a conflict arises such that some data must be removed - that is best left to the user.  So `dotfiles status` will indicate conflicting dotfiles and user must resolve them in whatever way is appropriate.

New version will hopefully be released in a week or so.

Cheers
