### ISSUE TITLE
Prefix handling is wierd

### ISSUE THREAD

**Issue by aviau** [jbernard/dotfiles#32]
Hey, thanks for the app!

So this is my dotfiles folder:

<pre>
~/git/dotfiles
├── .tmux.conf
├── .something_else.conf
└── bin
   └── some_script
</pre>

With the "prefix = . " option set, Dotfiles links "bin" to "~/.in".

I would like it to detect that "bin" does not start with "." (or whatever my specified prefix is) and should be linked to "~/bin"

I insist that my dotfiles folder should keep this format.

Thanks!

**Comment by jbernard** [comment]
This should all be resolved now in `master`, new major release coming shortly.
