### ISSUE TITLE
Optionally skip prefixing of files with .

### ISSUE THREAD

**Issue by IvanMalison** [jbernard/dotfiles#47]
This utility can easily be used for synchronizing arbitrary configuration folders with symlinks that may not necessarily be the home directory. I have encountered several use cases where the files that I want to manage with 'dotfiles' should not/can not be prefixed with a '.' . It would be great if there were an option to disable the insertion of a '.' at the beggining of synchronized filenames.

**Comment by jbernard** [comment]
Have you seen the `-s` option to the `cp` utility?  Combined with `-R`, it offers something very similar.  Is there a difference between that and the patch here?   I'm just curious.

**Comment by IvanMalison** [comment]
I did not know about that option. Does it symlink at the leaves of the target directory or at the top level?

In any case, I'm not sure I see how this question relates to the proposed pull request. If the -s flag can, in fact, provide the 'no dot' functionality, then it should also be able to provide the functionality offered by this repository in general with something like

find $source_dir -depth 1 | xargs -I filename cp -Rs filename "$target_dir/".filename

When I run cp -Rs I get errors, and it doesn't seem to do what I want. It's not clear to me that you really want the -R flag here. It seems like you would just want to run cp with -s on each file in the source directory which is different.

**Comment by jbernard** [comment]
It does symlink at the leaves, but you're right - it gives errors if the arguments are not perfect and falls down pretty quickly.  I was just thinking if you didn't need the `.` and the files in the repo were not dotfiles and you just needed symlinks without the other options and features - then you might find a simpler solution with `cp`.

**Comment by jbernard** [comment]
If I were to symlink at the leaves instead of the top level (removing the need for the packages feature), would that be a welcome change, or would you find it more frustrating?

**Comment by IvanMalison** [comment]
It seems like that would be a useful feature, but not a sensible default behavior. Its hard for me to think of a reason why you would want to symlink at the leaves rather than at the top level

**Comment by IvanMalison** [comment]
do you mind making a new pypi release for this?
