### ISSUE TITLE
adding subdirectories

### ISSUE THREAD

**Issue by florian-wagner** [jbernard/dotfiles#49]
Hey, I would like to sync just .vimrc and .vim/snippets not all the plugins in .vim/bundle, since they have compiled parts that don't work on all machines.

```
dotfiles -a .vim/snippets
```
returned "Not a dotfile". And
```
dotfiles -a .vim
```
in combination with
```
ignore = [
    '.git',
    '.gitignore',
    '*.swp',
    '.vim/bundle/*']
```
did not work either. Am I missing something here or is the inclusion of subdirectories not implemented yet?

**Comment by niol** [comment]
What I've proposed in #24 makes it easy to do this.

```
$ dotfiles -a ~/.config/vlc/
$ ls -la ~/.config/
total 16
drwx------  3 niol niol 4096 févr.  3 10:11 .
drwxr-xr-x 28 niol niol 4096 févr.  3 09:32 ..
drwx------  2 niol niol 4096 sept. 21  2012 htop
-rw-r--r--  1 niol niol 1926 janv.  2 18:21 Trolltech.conf
lrwxrwxrwx  1 niol niol   32 févr.  3 10:11 vlc -> ../.dotfiles/all.host/config/vlc
```

**Comment by jbernard** [comment]
I just added this (finally, i know) to `master`.  New major release should be out in a week or so.

Cheers
