### ISSUE TITLE
Best practices for differences between machines

### ISSUE THREAD

**Issue by florian-wagner** [jbernard/dotfiles#50]
I use dotfiles to keep my configuration in sync between machines. But sometimes the settings (have to) differ for example different terminal font settings because of different screen resolutions.

What is the best way to handle such small changes across machines, while keeping the most important settings in sync?

**Comment by niol** [comment]
- modularize your configuration : separate what is common to all machines and what is specific in different files. This depends on the conf file format and is not always possible. For instance, I have ```.bashrc.host1``` and ```.bashrc.host2``` and ```.bashrc``` loads one of those consistently with ```$(hostname)``` using this simple code:
```
if [ -r $HOME/.bashrc.$(hostname) ]; then
    source $HOME/.bashrc.$(hostname)
fi
```
- I have proposed host profiles in #24 which allows ```dotfiles``` to have multiple dot files configurations that can be synced separately.
- you an also use source control manager capabilities (for instance, ```git``` branches and merge).

**Comment by florian-wagner** [comment]
thanks, that helps a lot.
