### ISSUE TITLE
dot prefix bug?

### ISSUE THREAD

**Issue by ratson** [jbernard/dotfiles#53]
I have created a repo to demo the bug, please have a look at https://github.com/ratson/dotfiles-bug

**Comment by ratson** [comment]
@jbernard Do you have any hints about the issue? I will dig into the code to see if I could send a pull request this weekend, or you have planned to fix it already?

**Comment by jbernard** [comment]
@ratson Hey, thanks for the bug report.  I'm juggling so many things right now I'm not sure when I'll be able to look closer, maybe this weekend but you're certainly free to have a go at it.

**Comment by ratson** [comment]
While I am preparing the pull request, I find this duplicates with #33.
