### ISSUE TITLE
Dryrun doesn't always work and -m doesn't store the new location

### ISSUE THREAD

**Issue by 0xR** [jbernard/dotfiles#55]
I ran `dotfiles -m dotfiles --dry-run` this didn't do a dry run

Now my files are in the new directory, but executing `dotfiles -m Dotfiles` doesn't restore it because the dir Dotfiles doesn't exist.

I can fix it, but the user experience is not that great.

**Comment by jbernard** [comment]
Yes, I see now that's a bug.  I apologize and will get that fixed in the next release.

**Comment by jbernard** [comment]
You could specify the repository path with `-R`, as in `dotfiles -R dotfiles -m Dotfiles` to move it back, or re-sync with `dotfiles -R dotfiles -s`.

**Comment by jbernard** [comment]
This is fixed in `master`, along with a bunch of other changes and improvements.  New release should be up soon.

Cheers.
