### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by jbernard** [jbernard/dotfiles#57]
I would really like to make a simple site with documentation and it'd be great to have a modest logo and/or icon.  I'm rather terrible at that sort of thing, but if anyone has ideas or would like to contribute something, I would be very grateful.

Cheers

**Comment by prologic** [comment]
I'm terrible at logos and generally ui stuff too; but I can probably whip
up some kind of Pelican based static site that you could host on github.io
pages? See: http://vallinux.org/ for example (Source:
https://github.com/vallinux/vallinux.github.io)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by jbernard** [comment]
For me, making the site is no problem, but making it look decent with something visually interesting like a logo is where I would fall short.

**Comment by prologic** [comment]
Same :/


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by jbernard** [comment]
I'll not let a logo stop me ;) No worries.
