### ISSUE TITLE
`dotfile sync --force` removes `.config`.

### ISSUE THREAD

**Issue by yazgoo** [jbernard/dotfiles#62]
Hi,

running dotfiles v0.6.4 , I lost my .config content.
I think dotfile should not override a directory with a symlink.
For example, if in my dotfiles directory I have:

```
.config/nvim/init.vim
```

And I already have a file called:

```
.config/nvim/some-other-conf
```

`dotfile sync --force` should only add

```
.config/nvim/init.vim
```
As a symlink. Not the intermediate directories like `.config` and `.config/nvim`.

**Comment by yazgoo** [comment]
Looks like the version in master is safer, would you advise to use it @jbernard ?

Thanks for writing this tool

**Comment by yazgoo** [comment]
Using the version in master until next release !

**Comment by jbernard** [comment]
Hey, sorry for the delay.  Yes, the version in master addresses this issue by supporting nested directories and never issuing destructive operations such as `rm`, so I would recommend using that.  I apologize for the bug in 0.6.4, I really need to make a release from master, but I have a few things remaining to finish.  Let me know how the master version goes, if there's anything annoying or anything missing.

Cheers
