### ISSUE TITLE
Is an AUR update possible?

### ISSUE THREAD

**Issue by done-with-fish** [jbernard/dotfiles#72]
Would it be possible to update the AUR package? The package hasn't been updated in a few years.

**Comment by jbernard** [comment]
It’s certainly possible ;)  There are two versions:

  https://aur.archlinux.org/packages/dotfiles/
  https://aur.archlinux.org/packages/dotfiles-git/

The -git package could be updated, but I am not an Arch developer and I believe those packages are maintained by others.  I’m not sure what the process is to submit or request an update, but it’s certainly something I can look into at some point - how hard could it be ;)  Things are too busy for me right now, maybe you can ping the package owner?

**Comment by done-with-fish** [comment]
Yes will do!
